.TH FBAPPSELECT 1 "2025-08-26" "flux-tools 1.2.5" "User Commands"
.SH NAME
fbappselect \- application launcher for FluxBox desktop
.SH SYNOPSIS
.B fbappselect
.SH DESCRIPTION
.B fbappselect
displays a graphical application launcher using xlunch. It generates a grid-based menu showing available desktop applications with icons for easy selection.
.SH SEE ALSO
.BR xlunch (1),
.BR fluxbox (1)
.SH AUTHOR
Tomas-M <https://github.com/Tomas-M>
crims0n <crims0n@minios.dev>