.TH FBLIVEAPP 1 "2025-08-26" "flux-tools 1.2.5" "User Commands"
.SH NAME
fbliveapp \- live application installer for MiniOS
.SH SYNOPSIS
.B fbliveapp
.I application_name
.SH DESCRIPTION
.B fbliveapp
provides a localized interface for installing applications on MiniOS live systems. It supports multiple languages and provides application descriptions and installation commands.
.SH OPTIONS
.TP
.B vlc
Install VLC Video Player
.SH ENVIRONMENT
.TP
.B LANG
Determines the language for application descriptions
.SH SEE ALSO
.BR apt (8)
.SH AUTHOR
Tomas-M <https://github.com/Tomas-M>
crims0n <crims0n@minios.dev>