.TH FBMENU 1 "2025-08-26" "flux-tools 1.2.5" "User Commands"
.SH NAME
fbmenu \- keyboard layout selector for FluxBox
.SH SYNOPSIS
.B fbmenu
.SH DESCRIPTION
.B fbmenu
provides a graphical interface for selecting keyboard layouts. It detects the current locale and displays available keyboard layouts with country flags for easy identification.
.SH ENVIRONMENT
.TP
.B TEXTDOMAIN
Set to "flux-tools" for internationalization
.SH SEE ALSO
.BR setxkbmap (1),
.BR locale (1)
.SH AUTHOR
Tomas-M <https://github.com/Tomas-M>
crims0n <crims0n@minios.dev>