.TH FBPRINTSCREEN 1 "2025-08-26" "flux-tools 1.2.5" "User Commands"
.SH NAME
fbprintscreen \- take and display screenshots
.SH SYNOPSIS
.B fbprintscreen
.SH DESCRIPTION
.B fbprintscreen
captures a screenshot using scrot and displays it in a resized window using feh. The screenshot is saved to the ~/Pictures directory and displayed at 2/3 of the screen size.
.SH FILES
.TP
.I ~/Pictures
Directory where screenshots are saved
.SH SEE ALSO
.BR scrot (1),
.BR feh (1)
.SH AUTHOR
Tomas-M <https://github.com/Tomas-M>
crims0n <crims0n@minios.dev>