.TH FBSTARTUPNOTIFY 1 "2025-08-26" "flux-tools 1.2.5" "User Commands"
.SH NAME
fbstartupnotify \- provide visual feedback during application startup
.SH SYNOPSIS
.B fbstartupnotify
.RB [ false ]
.SH DESCRIPTION
.B fbstartupnotify
changes the mouse cursor to indicate application startup and automatically reverts it when a new window is detected. Provides visual feedback to users during application launching.
.SH OPTIONS
.TP
.B false
Reset cursor to normal without waiting for new windows
.SH SEE ALSO
.BR xsetroot (1),
.BR wmctrl (1)
.SH AUTHOR
Tomas-M <https://github.com/Tomas-M>
crims0n <crims0n@minios.dev>